### ISSUE TITLE
How to use this patch

### ISSUE THREAD

**Issue by atlantis414** [alexleigh/pve-mods#1]
Can you briefly list the command line

**Comment by alexleigh** [comment]
The command line is

```shell
patch [name of file to be patched] [name of patch file]
```

However I highly recommend manually editing the files, modifying my patches as needed for your particular configuration, rather than patching the files directly.

**Comment by alexleigh** [comment]
Closing this as resolved. Please open another issue if you have more questions about how to use these files.
