### ISSUE TITLE
Version for proxmox-widget-toolkit 3.7.0 planned?

### ISSUE THREAD

**Issue by mjschrod** [alexleigh/pve-mods#3]
Hi alexleigh,
thanks for your great work.
Are you planning a version for the recent version of proxmox-widget-toolkit 3.7.0?
A assume using one of your current version is not recommended... :)
Matthias

**Comment by alexleigh** [comment]
Thanks for bringing this to my attention. Added the patch directory for proxmox-widget-toolkit 3.7.0.
